version: "3.8"

services:
  bugsbunny:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - celerytest
    volumes:
      - "bugsbunny_data:/data"

networks:
  celerytest:

volumes:
  bugsbunny_data:
