# Generated by Django 3.0.8 on 2020-09-07 12:26

from django.db import migrations, models
import django.db.models.deletion
import faker.providers.lorem
import faker.providers.person
import faker.providers.python


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=faker.providers.person.Provider.name, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=faker.providers.lorem.Provider.sentence, max_length=150)),
                ('price', models.IntegerField(default=faker.providers.python.Provider.pyint)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bla', related_query_name='bla2', to='app2.Author')),
            ],
        ),
    ]
