# Generated by Django 3.0.5 on 2020-07-21 15:48

from django.db import migrations, models
import django.db.models.deletion
import faker.providers.python


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bla', models.CharField(default=faker.providers.python.Provider.pystr, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=faker.providers.python.Provider.pyint)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.A')),
            ],
        ),
    ]
