# Generated by Django 3.0.5 on 2020-07-21 15:56

from django.db import migrations, models
import faker.providers.python


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a',
            name='bla',
            field=models.CharField(default=faker.providers.python.Provider.pystr, max_length=250),
        ),
        migrations.AlterField(
            model_name='b',
            name='x',
            field=models.IntegerField(default=faker.providers.python.Provider.pyint),
        ),
    ]
