# Generated by Django 3.0.5 on 2020-07-21 16:12

from django.db import migrations, models
import django.db.models.deletion
import faker.providers.python


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200721_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a',
            name='bla',
            field=models.CharField(default=faker.providers.python.Provider.pystr, max_length=250),
        ),
        migrations.AlterField(
            model_name='b',
            name='x',
            field=models.IntegerField(default=faker.providers.python.Provider.pyint),
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=faker.providers.python.Provider.pystr, max_length=250)),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.B')),
            ],
        ),
    ]
