# Generated by Django 3.0.5 on 2020-07-22 09:47

import app1.models
from django.db import migrations, models
import django.db.models.deletion
import faker.providers.python


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200721_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meh', models.CharField(default=faker.providers.python.Provider.pystr, max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='a',
            name='bla',
            field=models.CharField(default=faker.providers.python.Provider.pystr, max_length=250),
        ),
        migrations.AlterField(
            model_name='b',
            name='x',
            field=models.IntegerField(default=faker.providers.python.Provider.pyint),
        ),
        migrations.AlterField(
            model_name='c',
            name='title',
            field=models.CharField(default=faker.providers.python.Provider.pystr, max_length=250),
        ),
        migrations.AddField(
            model_name='c',
            name='d',
            field=models.ForeignKey(default=app1.models.new_d, on_delete=django.db.models.deletion.CASCADE, to='app1.D'),
        ),
    ]
