version: "3.9"

services:

  postboard:
    container_name: postboard
    image: obsidiandynamics/kafka
    restart: "no"

    ports:
      - "2181:2181"
      - "9092:9092"

    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://postboard:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

    networks:
        - postboard-net

  postboard-stalker:
    container_name: postboard-stalker
    image: obsidiandynamics/kafdrop
    restart: "no"

    ports:
      - "9000:9000"

    environment:
      KAFKA_BROKERCONNECT: "postboard:29092"

    depends_on:
      - "postboard"

    networks:
        - postboard-net

networks:
    postboard-net:
